language: perl
perl:
  - 5.19
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - 5.10
  - 5.8
before_install:
  - cpanm -nq App::mymeta_requires
install:
  - (mymeta-requires --develop | cpanm -nq) || cat ~/.cpanm/build.log
script:
  - prove -lr xt
