language: perl
perl:
  - 5.26 
  - 5.24
  - 5.22
  - "5.20"
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - "5.10"
  - 5.8
matrix:
  allow_failures:
    - perl: 5.8
    - perl: 5.12
before_install:
  - perlbrew install-cpanm -f
install:
  - (cd App-cpanminus && cpanm -nq --installdeps --with-develop --with-recommends --with-suggests .)
  - (cd Menlo && cpanm -nq --installdeps --with-develop --with-recommends --with-suggests .)
script:
  - (cd App-cpanminus && prove -lr xt -j9)
sudo: false
